adminlte/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace adminlte.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string CompanyID { get; set; }
        [DisplayName("Company Name")]
        public string CompanyName { get; set; }
        [DisplayName("Company Location")]
        public string CompanyLocation { get; set; }
        [DisplayName("Company Fax")]
        public string CompanyFax { get; set; }
        [DisplayName("Company Tele-Phone")]
        public string CompanyTelePhone { get; set; }
        [DisplayName("About Company")]
        public string AboutCompany { get; set; }

        public virtual ICollection<Vehicle> Fleet { get; set; }
        public virtual ICollection<Travel> Travel_list { get; set; }
    }
}

adminlte/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using adminlte.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace adminlte.Controllers
{
    public class CompaniesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CompanyID,CompanyName,CompanyLocation,CompanyFax,CompanyTelePhone,AboutCompany")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //------------------------------------------------------------------------------------------------------------
        public ActionResult CreateBuses()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBuses(Bus bus)
        {
            if (ModelState.IsValid)
            {

                bus.BusID = User.Identity.GetUserId();
                bus.BusNumber = (db.Buses.Where(a => a.BusID == bus.BusID).ToList().Count() + 1).ToString();
                db.Buses.Add(bus);
                db.SaveChanges();
                return RedirectToAction("ManageBuses");
            }

            return View(bus);
        }
        //------------------------------------------------------------------------------------------------------------
        public ActionResult ManageBuses()
        {
            string id = User.Identity.GetUserId();
            return View(db.Buses.Where(a=>a.BusID == id).ToList());
        }
        //------------------------------------------------------------------------------------------------------------
        public ActionResult EditBus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBus(Bus bus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageBuses");
            }
            return View(bus);
        }
        //------------------------------------------------------------------------------------------------------------
        public ActionResult DeleteBus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("DeleteBus")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBus(int id)
        {
            Bus bus = db.Buses.Find(id);
            db.Buses.Remove(bus);
            db.SaveChanges();
            return RedirectToAction("ManageBuses");
        }

        //------------------------------------------------------------------------------------------------------------
        public ActionResult ManageDrivers()
        {
            string id = User.Identity.GetUserId();
            return View(db.PublicDrivers.Where(a => a.PublicDriverID == id).ToList());
        }
        //------------------------------------------------------------------------------------------------------------
        public ActionResult CreateDrivers()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDrivers(PublicDriver publicdriver, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                publicdriver.PublicDriverID = User.Identity.GetUserId();
                db.PublicDrivers.Add(publicdriver);

                if (upload != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    publicdriver.DriverImage = upload.FileName;
                }

                db.SaveChanges();
                return RedirectToAction("ManageDrivers");
            }

            return View(publicdriver);
        }
        //------------------------------------------------------------------------------------------------------------
        public ActionResult EditDriver(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PublicDriver publicdriver = db.PublicDrivers.Find(id);
            if (publicdriver == null)
            {
                return HttpNotFound();
            }
            return View(publicdriver);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditDriver(PublicDriver publicdriver)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publicdriver).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageDrivers");
            }
            return View(publicdriver);
        }
        //------------------------------------------------------------------------------------------------------------
        public ActionResult DeleteDriver(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PublicDriver publicdriver = db.PublicDrivers.Find(id);
            if (publicdriver == null)
            {
                return HttpNotFound();
            }
            return View(publicdriver);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("DeleteDriver")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDriver(int id)
        {
            PublicDriver publicdriver = db.PublicDrivers.Find(id);
            db.PublicDrivers.Remove(publicdriver);
            db.SaveChanges();

adminlte/Views/Companies/Create.cshtml
@model adminlte.Models.Company

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Company</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyLocation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyLocation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyLocation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyFax, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyFax, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyFax, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyTelePhone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyTelePhone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyTelePhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AboutCompany, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AboutCompany, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AboutCompany, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>

adminlte/Views/Companies/CreateDrivers.cshtml
@model adminlte.Models.PublicDriver

@{
    ViewBag.Title = "CreateDrivers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>CreateDrivers</h2>

    @using (Html.BeginForm("CreateDrivers", "Companies", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>PublicDriver</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.PublicDriverID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PublicDriverID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PublicDriverID, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.DriverName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DriverName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DriverName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DriverLastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DriverLastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DriverLastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DriverNationalID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DriverNationalID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DriverNationalID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DriverPhone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DriverPhone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DriverPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DriverImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="upload" />
                    @Html.ValidationMessageFor(model => model.DriverImage, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
                @Html.LabelFor(model => model.IDVehicle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDVehicle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDVehicle, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "ManageDrivers")
    </div>
    </div>

adminlte/Views/Companies/Dashboard.cshtml
@using Microsoft.AspNet.Identity
@using adminlte.Models

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var db = new ApplicationDbContext();
    string company_id = ViewBag.ComID;
    var company = db.Companies.Where(a => a.CompanyID == company_id).SingleOrDefault();
}


<div class="content-wrapper">

    <h2>@company.CompanyName Dashboard</h2>
    <h1 style="margin-bottom:20px; color:mediumvioletred">Public transportaion travels </h1>

    <div class="row panel-body">
        <div class="row">
            @{
                var travel_list = db.Travels.Where(a => a.IDCompany == company.Id).ToList();
                if (travel_list.Count > 0)
                {
                    foreach (var subItem in travel_list)
                    {
                        var passenger = db.Passengers.Where(a=>a.IDCompany == company.Id && a.PassengerID == "").ToList();
                        <div class="col-md-3 thumbnail img-size" style="margin-right:20px; margin-left:20px; margin-bottom:30px; min-height:150px">
                            <img src="~/images/bus.png" width="75px" height="75px" />
                            <h3>
                                Location: @Html.DisplayFor(modelItem => subItem.Location)
                            </h3>
                            <h3>
                                Destination: @Html.DisplayFor(modelItem => subItem.Destination)
                            </h3>
                            <h4>
                                Leave time: @Html.DisplayFor(modelItem => subItem.Leavetime)
                            </h4>
                            <h4>
                                Booked sits: @Html.DisplayFor(modelItem => subItem.PassengerNumber)
                            </h4>

                           

                            @Html.ActionLink("More details", "TransportationDetails", "Companies", new { TravelID = subItem.Id }, new { @class = "btn btn-primary" })
                        </div>
                    }
                }
                else
                {
                    <div class="col-md-12" style="margin-right:20px; margin-left:20px; margin-bottom:30px; min-height:150px">
                        <h3>
                            No travels are available yet for this company!
                        </h3>
                    </div>
                }
            }
        </div>

    </div>
</div>

adminlte/Views/Companies/DeleteBus.cshtml
@model adminlte.Models.Bus

@{
    ViewBag.Title = "DeleteBus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>DeleteBus</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Bus</h4>
        <hr />
        <dl class="dl-horizontal">


            <dt>
                @Html.DisplayNameFor(model => model.BusModel)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BusModel)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BusPlate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BusPlate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BusColor)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BusColor)
            </dd>


        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "ManageBuses")
            </div>
        }
    </div>
    </div>

adminlte/Views/Companies/DeleteDriver.cshtml
@model adminlte.Models.PublicDriver

@{
    ViewBag.Title = "DeleteDriver";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>DeleteDriver</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>PublicDriver</h4>
        <hr />
        <dl class="dl-horizontal">


            <dt>
                @Html.DisplayNameFor(model => model.DriverName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DriverName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DriverLastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DriverLastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DriverNationalID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DriverNationalID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DriverPhone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DriverPhone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DriverImage)
            </dt>

            <dd>
                <img src="~/uploads/@Html.DisplayFor(model=>model.DriverImage)" class="thumbnail"
                     style="width:48px; height:48px;" />
            </dd>



        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "ManageDrivers")
            </div>
        }
    </div>
    </div>

adminlte/Views/Companies/DeleteTravel.cshtml
@model adminlte.Models.Travel
@using Microsoft.AspNet.Identity
@using adminlte.Models

@{
    ViewBag.Title = "DeleteTravel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var db = new ApplicationDbContext();
    var travel = db.Travels.Where(a => a.Id == Model.Id).SingleOrDefault();

    var vehicle = db.Vehicles.Where(a => a.Id == travel.IDVehicle).SingleOrDefault();

    var BUS = db.Buses.Where(a => a.Id == vehicle.IDBus).SingleOrDefault();

    var DRIVER = db.PublicDrivers.Where(a => a.Id == vehicle.IDPublicDriver).SingleOrDefault();
}

<div class="content-wrapper">
    <h2>DeleteTravel</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Travel</h4>
        <hr />
        <dl class="dl-horizontal">           

            <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Destination)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Destination)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Leavetime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Leavetime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Notes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Notes)
            </dd>
            

            <dt>
                Driver name
            </dt>

            <dd>
                @DRIVER.DriverName
            </dd>
            <dt>
                Driver Last name
            </dt>

            <dd>
                @DRIVER.DriverLastName 
            </dd>

            <dt>
                Bus Model
            </dt>

            <dd>
                @BUS.BusModel
            </dd>

            <dt>
                Bus Plate
            </dt>

            <dd>
                @BUS.BusPlate
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

adminlte/Views/Companies/TransportationDetails.cshtml
@model adminlte.Models.Travel
@using adminlte.Models

@{
    ViewBag.Title = "TransportationDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var db = new ApplicationDbContext();

    var vehicle = db.Vehicles.Where(a => a.Id == Model.IDVehicle).SingleOrDefault();

    var passenger = db.Passengers.Where(a => a.IDTravel == Model.Id).ToList();

    var BUS = db.Buses.Where(a => a.Id == vehicle.IDBus).SingleOrDefault();

    var DRIVER = db.PublicDrivers.Where(a => a.Id == vehicle.IDPublicDriver).SingleOrDefault();


}
<div class="content-wrapper">
    <h2>Transportation Details</h2>
    <div class="row ">
        <div>
 
            <dl class="dl-horizontal col-md-3">

                <dt>
                    @Html.DisplayNameFor(model => model.Location)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Location)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Destination)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Destination)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Leavetime)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Leavetime)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Notes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Notes)
                </dd>



            </dl>
        </div>
        <div>

      
            <dl class="dl-horizontal col-md-3">


                <dt>
                    Driver name
                </dt>

                <dd>
                    @DRIVER.DriverName
                </dd>
                <dt>
                    Driver Last name
                </dt>

                <dd>
                    @DRIVER.DriverLastName
                </dd>

                <dt>
                    Bus Model
                </dt>

                <dd>
                    @BUS.BusModel
                </dd>

                <dt>
                    Bus Plate
                </dt>

                <dd>
                    @BUS.BusPlate
                </dd>

            </dl>
        </div>
        <div>
            <dl class="dl-horizontal col-md-3">


                <dt>
                    @Html.DisplayNameFor(model => model.PassengerNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PassengerNumber)
                </dd>

            </dl>
        </div>
    </div>
   

    <h3>  Passenger list</h3>
    <table class="table">
        <tr>           
            <th>
               User Name
            </th>
            <th>
                Last Name
            </th>
            <th>
               BOD
            </th>
            <th>
               Address
            </td>

            <th>
                Mobile
            </th>

            <th>
                Booked sits
            </th>

            <th>option</th>
        </tr>

        @foreach (var item in passenger)
        {


            var user = db.Clients.Where(a => a.IDUser == item.IDUser).SingleOrDefault();
            <tr>
               
                <td>
                    @Html.DisplayFor(modelItem => user.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.DOB)
                </td>
                <td>
                   @Html.DisplayFor(modelItem => user.Address)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => user.Mobile)
                </td>

                <td>
                    @item.SitNumber
                </td>

                <td>
                    @Html.ActionLink("Cancel reservation", "Cancelreservation", new { passengerID = item.Id })
                </td>
            </tr>
        }
        `
    </table>


    <p>
        @Html.ActionLink("Back to List", "Dashboard", "Companies") 
    </p>
</div>