adminlte/Controllers/TransportationController.cs
using adminlte.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace adminlte.Controllers
{
    public class TransportationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transportation
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PublicTransportation()
        {
            return View();
        }

        public ActionResult TransportationDetails(int? TravelID)
        {
            var travel = db.Travels.Where(a => a.Id == TravelID).SingleOrDefault();
            return View(travel);
        }
         
        public ActionResult Book_Transportaion(int? TravelID)
        {
            var travel = db.Travels.Where(a => a.Id == TravelID).SingleOrDefault();
            ViewBag.TravelData = travel;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Book_Transportaion(Passenger passenger,int travelid)
        {
            string userid = User.Identity.GetUserId();
            var Travel = db.Travels.Where(a => a.Id == travelid).SingleOrDefault();
            var company = db.Companies.Where(a => a.Id == Travel.IDCompany).SingleOrDefault();

            var bookcheck = db.Passengers.Where(a => a.IDUser == userid && a.IDTravel == Travel.Id).ToList();

            if (bookcheck.Count>0)
            {
                ViewBag.message = "You have already applied for this travel!";
                ViewBag.TravelData = Travel;
                return View();
            }
            else
            {

                if (int.Parse(passenger.SitNumber)<11)
                {
                    if (int.Parse(passenger.SitNumber) < 46 -Travel.PassengerNumber )
                    {
                        passenger.IDUser = userid;
                        passenger.IDTravel = Travel.Id;
                        passenger.IDCompany = Travel.IDCompany;

                        db.Passengers.Add(passenger);
                        db.SaveChanges();

                        Travel.PassengerNumber += int.Parse(passenger.SitNumber);
                        db.SaveChanges();

                        MailBox mail = new MailBox();
                        string Message = "Your reservation is applied successfully, please don't miss the bus "+ Travel.Location + "/" + Travel.Destination+ " @ " + Travel.Leavetime;
                        mail.Message = Message;
                        mail.Subject = "Book a public transportation";
                        mail.TargetID = userid;
                        mail.Sender = company.CompanyName;
                        mail.SenderID = company.CompanyID;
                        mail.TimeStamp = System.DateTime.Now.ToString();
                        db.MailBoxes.Add(mail);
                        db.SaveChanges();

                        return RedirectToAction("index", "Home");
                    }
                    else
                    {
                        var n = 45 - @Travel.PassengerNumber;

                        ViewBag.message = "This travel has only (" + n + ") sits available" ;
                        ViewBag.TravelData = Travel;
                        return View();
                    }
                   
                }
                else
                {
                    ViewBag.message = "You are not allowed to book more than 10 sits!";
                    ViewBag.TravelData = Travel;
                    return View();
                }

                
            }

        }
        //--------------------------------------------------------------------------------
    }
}

adminlte/Views/Transportation/Book_Transportaion.cshtml
@model adminlte.Models.Passenger
@using adminlte.Models

@{
    ViewBag.Title = "Book_Transportaion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ 
    var db = new ApplicationDbContext();
    var travel = ViewBag.TravelData;

    int travelid = travel.IDVehicle;

    var vehicle = db.Vehicles.Where(a => a.Id == travelid).SingleOrDefault();

    var BUS = db.Buses.Where(a => a.Id == vehicle.IDBus).SingleOrDefault();

    var DRIVER = db.PublicDrivers.Where(a => a.Id == vehicle.IDPublicDriver).SingleOrDefault();
}

<div class="content-wrapper">
    <h2>Book Transportaion</h2>

    <div>
        @{
            if (ViewBag.message != null)
            {
                <h3 style="color:seagreen">@ViewBag.message</h3>
            }
        }
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div>
            <h4>Travel</h4>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    Location
                </dt>

                <dd>
                    @travel.Location
                </dd>

                <dt>
                    Destination
                </dt>

                <dd>
                    @travel.Destination
                </dd>

                <dt>
                    Leavetime
                </dt>

                <dd>
                    @travel.Leavetime
                </dd>

                <dt>
                    Notes
                </dt>

                <dd>
                    @travel.Notes
                </dd>


                <dt>
                    Driver name
                </dt>

                <dd>
                    @DRIVER.DriverName
                </dd>
                <dt>
                    Driver Last name
                </dt>

                <dd>
                    @DRIVER.DriverLastName
                </dd>

                <dt>
                    Bus Model
                </dt>

                <dd>
                    @BUS.BusModel
                </dd>

                <dt>
                    Bus Plate
                </dt>

                <dd>
                    @BUS.BusPlate
                </dd>

            </dl>
        </div>

        <div class="form-horizontal" >
            <h4>Passenger</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" >
                @Html.LabelFor(model => model.SitNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.SitNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SitNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Book" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "PublicTransportation")
    </div>
    </div>

adminlte/Views/Transportation/PublicTransportation.cshtml
@using Microsoft.AspNet.Identity
@using adminlte.Models

@{
ViewBag.Title = "PublicTransportation";
Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
 
<h1 style="margin-bottom:20px; color:mediumvioletred">Public transportaion travels </h1>

@{
var db = new ApplicationDbContext();
var company_list = db.Companies.ToList();
}
<div class="row panel-body">
@if (company_list.Count > 0)
{
    foreach (var Item in company_list)
    {
        <div class="panel-heading alert alert-info">
            <h1>@Item.CompanyName</h1>
        </div>
        <div class="row">
           @{
            var travel_list = db.Travels.Where(a => a.IDCompany == Item.Id).ToList();
            if (travel_list.Count > 0)
            {
            foreach (var subItem in travel_list)
            {
            var company = db.Companies.Where(a => a.Id == subItem.IDCompany).SingleOrDefault();
            <div class="col-md-3 thumbnail img-size" style="margin-right:20px; margin-left:20px; margin-bottom:30px; min-height:150px">
                <img src="~/images/bus.png" width="150px" height="150px" />
                <h3>
                    Location: @Html.DisplayFor(modelItem => subItem.Location)
                </h3>
                <h3>
                    Destination: @Html.DisplayFor(modelItem => subItem.Destination)
                </h3>
                <h4>Leavetime: @Html.DisplayFor(modelItem => subItem.Leavetime)</h4>
                <h5>@Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => subItem.company).ToString()))</h5>

                @Html.ActionLink("More details", "TransportationDetails", "Transportation", new { TravelID = subItem.Id }, new { @class = "btn btn-primary" })
            </div>
            }
            }
            else
            {
            <div class="col-md-12" style="margin-right:20px; margin-left:20px; margin-bottom:30px; min-height:150px">
                <h3>
                    No travels are available yet for this company!
                </h3>
            </div>
            }
            }
            </div>
    }
}
        </div>
</div>

adminlte/Views/Transportation/TransportationDetails.cshtml
@model adminlte.Models.Travel
@using adminlte.Models

@{
    ViewBag.Title = "TransportationDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var db = new ApplicationDbContext();

    var vehicle = db.Vehicles.Where(a => a.Id == Model.IDVehicle).SingleOrDefault();

    var BUS = db.Buses.Where(a => a.Id == vehicle.IDBus).SingleOrDefault();

    var DRIVER = db.PublicDrivers.Where(a => a.Id == vehicle.IDPublicDriver).SingleOrDefault();
}
<div class="content-wrapper">
    <h2>Transportation Details</h2>

    <div>
        <h4>Travel</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Destination)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Destination)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Leavetime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Leavetime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Notes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Notes)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.PassengerNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PassengerNumber)
            </dd>


            <dt>
                Driver name
            </dt>

            <dd>
                @DRIVER.DriverName
            </dd>
            <dt>
                Driver Last name
            </dt>

            <dd>
                @DRIVER.DriverLastName
            </dd>

            <dt>
                Bus Model
            </dt>

            <dd>
                @BUS.BusModel
            </dd>

            <dt>
                Bus Plate
            </dt>

            <dd>
                @BUS.BusPlate
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Back to List", "PublicTransportation", "Transportation") |
        @Html.ActionLink("Book a place", "Book_Transportaion", "Transportation", new { TravelID = Model.Id }, new { @class = "btn btn-primary" })
       
    </p>
    </div>