adminlte/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace adminlte.Models
{
    public class Ticket
    {
        public int id { get; set; }
        public int DriverID { get; set; }
        public int OrderID { get; set; }
        public bool State { get; set; }
        public DateTime OpenTime { get; set; }
        public DateTime CloseTime { get; set; }
    }
}

adminlte/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using adminlte.Models;
using Microsoft.AspNet.Identity;

namespace adminlte.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tickets
        public ActionResult Index()
        {
            return View(db.Tickets.ToList());
        }

        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,UserID,BusID,State,OpenTime,CloseTime")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Tickets.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,UserID,BusID,State,OpenTime,CloseTime")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);

            var order = db.Orders.Where(a => a.Id == ticket.OrderID).SingleOrDefault();
            var privatedriver = db.PrivateDrivers.Where(a => a.Id == ticket.DriverID).SingleOrDefault();
            db.Tickets.Remove(ticket);
            db.SaveChanges();

            order.IDTicket = 0;
            db.SaveChanges();
            privatedriver.Availability = true;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult CreateTicket()
        {
            string id = User.Identity.GetUserId();
            ViewBag.privateDrivers = db.PrivateDrivers.Where(a => a.Availability == true).ToList();
            ViewBag.Orders = db.Orders.Where(a => a.IDTicket == 0).ToList();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTicket(Ticket ticket)
        {
            try
            {
                Ticket Tic = new Ticket();

                var OrderData = Request.Form["OrderData"].ToString();
                var DriverData = Request.Form["privateDrivers"].ToString();

                var Order_data = OrderData.Split(' ');
                var driver_data = DriverData.Split('/');
                var location = Order_data[0].Trim();
                var distination = Order_data[1].Trim();
                var time = Order_data[2].Trim();

                var driver_name = driver_data[0].Trim();
                var driver_lastname = driver_data[1].Trim();

                var order = db.Orders.Where(a => a.Location == location && a.Distination == distination).SingleOrDefault();
                var privatedriver = db.PrivateDrivers.Where(a => a.DriverName == driver_name && a.DriverLastName == driver_lastname).SingleOrDefault();
 
                Tic.DriverID = privatedriver.Id;
                Tic.OrderID = order.Id;
                Tic.State = true;
                Tic.OpenTime = System.DateTime.Now;
                Tic.CloseTime = System.DateTime.Now;
                db.Tickets.Add(Tic);

                db.SaveChanges();

                order.IDTicket = Tic.id;
                db.SaveChanges();
                privatedriver.Availability = false;
                db.SaveChanges();


                MailBox mail = new MailBox();
                string Message = "Your driver is "+ driver_name +" "+ driver_lastname + ", please don't miss the appointment from " + location + "to " + distination + " @ " + time;
                mail.Message = Message;
                mail.Subject = "Taxi reservation";
                mail.TargetID = order.IDUser;
                mail.Sender = "Admin";
                mail.SenderID = "";
                mail.TimeStamp = System.DateTime.Now.ToString();
                db.MailBoxes.Add(mail);
                db.SaveChanges();

                MailBox mail_driver = new MailBox();
                string Message_driver = "You have an appointment at " + time + " from " + location + " to " + distination +", with Mr. ";
                mail_driver.Message = Message_driver;
                mail_driver.Subject = "Taxi reservation";
                mail_driver.TargetID = privatedriver.PrivateDriverID;
                mail_driver.Sender = "Admin";
                mail_driver.SenderID = "";
                mail_driver.TimeStamp = System.DateTime.Now.ToString();
                db.MailBoxes.Add(mail_driver);
                db.SaveChanges();

                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("index");
            }
        }
    }
}

adminlte/Views/Tickets/Create.cshtml
@model adminlte.Models.Ticket

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Ticket</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })




            <div class="form-group">
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.State)
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OpenTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OpenTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OpenTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CloseTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CloseTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CloseTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>

adminlte/Views/Tickets/CreateTicket.cshtml
@model adminlte.Models.Ticket

@{
    ViewBag.Title = "CreateTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Create Ticket</h2>

    @using (Html.BeginForm("CreateTicket", "Tickets", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
       

        <div class="form-horizontal">
            <h4>Tickets</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.Label("Drivers", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        List<SelectListItem> listItems_drivers = new List<SelectListItem>();
                        if (ViewBag.privateDrivers != null)
                        {
                            foreach (var item in ViewBag.privateDrivers)
                            {
                                listItems_drivers.Add(new SelectListItem
                                {
                                    Text = item.DriverName + "/ " + item.DriverLastName,
                                    Value = item.DriverName + "/ " + item.DriverLastName
                                });
                            }
                        }

                    }

                    @Html.DropDownList("privateDrivers", listItems_drivers, "-- Select driver please --")
                </div>
            </div>


            <div class="form-group">
                @Html.Label("Orders", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        List<SelectListItem> listItems_orders = new List<SelectListItem>();
                        if (ViewBag.Orders != null)
                        {
                            foreach (var item in ViewBag.Orders)
                            {
                                listItems_orders.Add(new SelectListItem
                                {
                                    Text = item.Location + " " + item.Distination + " " + item.Time,
                                    Value = item.Location + " " + item.Distination + " " + item.Time
                                });
                            }
                        }

                    }

                    @Html.DropDownList("OrderData", listItems_orders, "-- Select order please --")
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
                        }

    <div>
        @Html.ActionLink("Back to List", "index")
    </div>
</div>

adminlte/Views/Tickets/Delete.cshtml
@model adminlte.Models.Ticket

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Ticket</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.OrderID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DriverID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DriverID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.State)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.State)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OpenTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OpenTime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CloseTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CloseTime)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

adminlte/Views/Tickets/Details.cshtml
@model adminlte.Models.Ticket

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Details</h2>

    <div>
        <h4>Ticket</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.OrderID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DriverID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DriverID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.State)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.State)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OpenTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OpenTime)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CloseTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CloseTime)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

adminlte/Views/Tickets/Edit.cshtml
@model adminlte.Models.Ticket

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Ticket</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.OrderID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OrderID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OrderID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DriverID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DriverID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DriverID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.State)
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OpenTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OpenTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OpenTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CloseTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CloseTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CloseTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>

adminlte/Views/Tickets/Index.cshtml
@model IEnumerable<adminlte.Models.Ticket>
@using adminlte.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new ApplicationDbContext();
    
}
<div class="content-wrapper">
    <h2>Index</h2>

 
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderID)
            </th>
            <th>
                Assigned Driver
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OpenTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CloseTime)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderID)
                </td>
                <td>
                    @{
                        var driver = db.PrivateDrivers.Where(a => a.Id == item.DriverID).SingleOrDefault();

                    }
                    @driver.DriverName  @driver.DriverLastName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OpenTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CloseTime)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>
    </div>